src/main/java/edu/wustl/mir/ctt/beans/AddEventBean.java
package edu.wustl.mir.ctt.beans;

import edu.wustl.mir.ctt.Controller;
import edu.wustl.mir.ctt.model.ECPEventTypes;
import edu.wustl.mir.ctt.model.ECPEvents;
import edu.wustl.mir.ctt.model.Event;
import edu.wustl.mir.ctt.model.StudyArmStatus;
import edu.wustl.mir.ctt.notification.NotificationException;
import edu.wustl.mir.ctt.persistence.PersistenceException;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

/**
 *
 * @author drm
 */
@ManagedBean
@RequestScoped
public class AddEventBean implements Serializable {
    private ECPEventTypes eventType;
    private Date dateOfOccurance;
    private String title;
    
    @ManagedProperty(value="#{controller}")
    private Controller controller;
    
    public AddEventBean() {
    }
    
    public List<ECPEventTypes> getEventTypes() {
        StudyArmStatus sas = controller.getSelectedParticipant().getStudyArmStatus();
        if("Observational Arm".equals(sas.getName())){
            return ECPEventTypes.getObservationalArmUnscheduledEvents();
        } else {
            return ECPEventTypes.getUnscheduledEvents();
        }
    }

    public ECPEventTypes getEventType() {
        return eventType;
    }

    public void setEventType(ECPEventTypes eventType) {
        this.eventType = eventType;
    }
    
    public String addEventAction() throws PersistenceException, NotificationException {
        // NOTE: If the event happens to be a Change in Therapy, the Change in Therapy form does not get populated with a copy of most of the baseline therapy values
        // or the Change in Therapy until the Change in Therapy form is read (See JDBCPersistenceManager.getChangeTherapyForm for details relating to copying the Baseline
        // or Change values to the newly created Change in Therapy form).
        Event e = ECPEvents.getInstance(eventType);
        System.out.println("The addEventAction eventType is: " + eventType.getName() + "  " + eventType.name());
        e.setActualDate( dateOfOccurance);
        
        return controller.insertEventAction( e);
    }

    public Date getDateOfOccurance() {
        return dateOfOccurance;
    }

    public void setDateOfOccurance(Date dateOfOccurance) {
        this.dateOfOccurance = dateOfOccurance;
    }
    
    public void setController(Controller c) {
        this.controller = c;
    }
    
    public Controller getController() {
        return controller;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}

src/main/java/edu/wustl/mir/ctt/beans/AddFormBean.java
package edu.wustl.mir.ctt.beans;

import edu.wustl.mir.ctt.AEController;
import edu.wustl.mir.ctt.Controller;
import edu.wustl.mir.ctt.form.AdverseEventWorksheetSAEForm;
import edu.wustl.mir.ctt.form.BasicForm;
import edu.wustl.mir.ctt.model.ECPEventTypes;
import edu.wustl.mir.ctt.model.ECPEvents;
import edu.wustl.mir.ctt.model.ECPFormTypes;
import edu.wustl.mir.ctt.model.Event;
import edu.wustl.mir.ctt.model.EventStatus;
import edu.wustl.mir.ctt.model.FormStatus;
import edu.wustl.mir.ctt.notification.NotificationException;
import edu.wustl.mir.ctt.persistence.PersistenceException;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;

/**
 *
 * @author drm
 */
@ManagedBean
@RequestScoped
public class AddFormBean implements Serializable {
    private Event event;
    private ECPFormTypes formType;
    private Date dateOfOccurance;
    private String title;
    
    @ManagedProperty(value="#{controller}")
    private Controller controller;
    
    public AddFormBean() {
    }
    
    @PostConstruct
    public void init() {
        // Automatically put today's date into the Add SAE Follow-up Form popup window.
        dateOfOccurance = new Date();
        event = controller.getSelectedEvent();
    }
    
    
    public List<ECPFormTypes> getFormTypes() {
        return event.getType().getUnscheduledFormTypes();
    }

    public ECPFormTypes getFormType() {
        return formType;
    }

    public void setFormType(ECPFormTypes formType) {
        this.formType = formType;
    }
    
    public String addFormAction() throws PersistenceException, NotificationException {
        BasicForm form = ECPFormTypes.getInstance(formType, event);
        form.setDate(dateOfOccurance);
        // Set the current date to be the same as the Form Date (dateOfOccurrance) found in the Add SAE Follow-up Form popup window.
        AdverseEventWorksheetSAEForm aews = (AdverseEventWorksheetSAEForm) form;
        aews.setCurrentDate(dateOfOccurance);
        // The newly created form needs to be inserted into the database before the event status can be updated.
        String eventSummaryPage = controller.insertFormAction( event, aews);
        // If you try to update the event status before inserting the new form, the status will be only from the
        // previously created forms.  The idea is to update the event status to be NEW when a new form is added.
        // The updateEventStatus gets the forms from the database for the particular event passed to it.  The 
        // status of each form is checked to determine the lowest status precedence, and the lowest status is 
        // used to determine the event status.
        controller.updateEventStatus(event);
        
        return eventSummaryPage;
    }

    public Date getDateOfOccurance() {
        return dateOfOccurance;
    }

    public void setDateOfOccurance(Date dateOfOccurance) {
        this.dateOfOccurance = dateOfOccurance;
    }
    
    public void setController(Controller c) {
        this.controller = c;
    }
    
    public Controller getController() {
        return controller;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}

src/main/java/edu/wustl/mir/ctt/beans/ValidateEvaluationFreshness.java
package edu.wustl.mir.ctt.beans;

import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;

/**
 *
 * @author drm
 */
 @ManagedBean
 @RequestScoped
public class ValidateEvaluationFreshness extends ValidateEvaluationsBean {
     
    @Override
    public boolean validateValues(FacesContext fc, List<UIInput> components, List<Object> values) {
        
        init( fc, components, values);
                            
        return ! studyArmEligibilityCalculator.isDataStale();
    }
    
}

src/main/java/edu/wustl/mir/ctt/form/CrossoverEligibilityWorkSheet.java
package edu.wustl.mir.ctt.form;

import edu.wustl.mir.ctt.model.AttributeDate;
import edu.wustl.mir.ctt.model.AttributeFloat;
import edu.wustl.mir.ctt.model.ECPFormTypes;
import edu.wustl.mir.ctt.model.PulmonaryEvaluation;
import edu.wustl.mir.ctt.model.VerificationStatus;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CrossoverEligibilityWorkSheet extends BasicForm {
    
    public static final String[] SourceDocumentTypes = new String[]{"History and Physical or Consultation Note", "Operative Report of Transplant Procedure", "Pulmonary Function Test Reports (for each FEV-1 submitted)"};
    
    private String pid;
    
    public CrossoverEligibilityWorkSheet() {
        super();
        this.formType = ECPFormTypes.CROSSOVER_ELIGIBILITY_WORKSHEET;
        title = "Crossover Eligibility Work Sheet";
        this.sourceDocumentTypes = SourceDocumentTypes;
        
        attributes.put("date1", new AttributeDate("date1", true, false, true));
        attributes.put("date2", new AttributeDate("date2", true, false, true));
        attributes.put("date3", new AttributeDate("date3", true, false, true));
        attributes.put("date4", new AttributeDate("date4", true, false, true));
        attributes.put("date5", new AttributeDate("date5", true, false, true));
        attributes.put("date6", new AttributeDate("date6"));
        attributes.put("date7", new AttributeDate("date7"));
        attributes.put("date8", new AttributeDate("date8"));
        attributes.put("date9", new AttributeDate("date9"));
        attributes.put("date10", new AttributeDate("date10"));
        attributes.put("date11", new AttributeDate("date11"));
        attributes.put("date12", new AttributeDate("date12"));
        attributes.put("date13", new AttributeDate("date13"));
        attributes.put("date14", new AttributeDate("date14"));
        attributes.put("date15", new AttributeDate("date15"));
        attributes.put("fev11", new AttributeFloat("fev11", true, false, true));
        attributes.put("fev12", new AttributeFloat("fev12", true, false, true));
        attributes.put("fev13", new AttributeFloat("fev13", true, false, true));
        attributes.put("fev14", new AttributeFloat("fev14", true, false, true));
        attributes.put("fev15", new AttributeFloat("fev15", true, false, true));
        attributes.put("fev16", new AttributeFloat("fev16"));
        attributes.put("fev17", new AttributeFloat("fev17"));
        attributes.put("fev18", new AttributeFloat("fev18"));
        attributes.put("fev19", new AttributeFloat("fev19"));
        attributes.put("fev110", new AttributeFloat("fev110"));
        attributes.put("fev111", new AttributeFloat("fev111"));
        attributes.put("fev112", new AttributeFloat("fev112"));
        attributes.put("fev113", new AttributeFloat("fev113"));
        attributes.put("fev114", new AttributeFloat("fev114"));
        attributes.put("fev115", new AttributeFloat("fev115"));
        attributes.put("fvc1", new AttributeFloat("fvc1", true, false, true));
        attributes.put("fvc2", new AttributeFloat("fvc2", true, false, true));
        attributes.put("fvc3", new AttributeFloat("fvc3", true, false, true));
        attributes.put("fvc4", new AttributeFloat("fvc4", true, false, true));
        attributes.put("fvc5", new AttributeFloat("fvc5", true, false, true));
        attributes.put("fvc6", new AttributeFloat("fvc6"));
        attributes.put("fvc7", new AttributeFloat("fvc7"));
        attributes.put("fvc8", new AttributeFloat("fvc8"));
        attributes.put("fvc9", new AttributeFloat("fvc9"));
        attributes.put("fvc10", new AttributeFloat("fvc10"));
        attributes.put("fvc11", new AttributeFloat("fvc11"));
        attributes.put("fvc12", new AttributeFloat("fvc12"));
        attributes.put("fvc13", new AttributeFloat("fvc13"));
        attributes.put("fvc14", new AttributeFloat("fvc14"));
        attributes.put("fvc15", new AttributeFloat("fvc15"));
        
        attributes.put("slope", new AttributeFloat("slope"));
        attributes.put("significance", new AttributeFloat("significance"));
    }
	
    public CrossoverEligibilityWorkSheet( BasicForm bf) {
        super(bf);
        this.formType = ECPFormTypes.CROSSOVER_ELIGIBILITY_WORKSHEET;
        title = bf.getTitle();
        this.sourceDocumentTypes = SourceDocumentTypes;
    }
    
    // This work sheet is normally created from values in the log.
    public CrossoverEligibilityWorkSheet( String pid, ObservePulmEvalLogForm log) {
        this();
        List<PulmonaryEvaluation> pulmEvals = log.getPulmEvaluations();
        this.pid = pid;
                    
        int i = 0;
        if(i < pulmEvals.size()){
            setDate1(pulmEvals.get(0).getDate());
            setFev11(pulmEvals.get(0).getFev1());
            setFvc1(pulmEvals.get(0).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate2(pulmEvals.get(1).getDate());
            setFev12(pulmEvals.get(1).getFev1());
            setFvc2(pulmEvals.get(1).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate3(pulmEvals.get(2).getDate());
            setFev13(pulmEvals.get(2).getFev1());
            setFvc3(pulmEvals.get(2).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate4(pulmEvals.get(3).getDate());
            setFev14(pulmEvals.get(3).getFev1());
            setFvc4(pulmEvals.get(3).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate5(pulmEvals.get(4).getDate());
            setFev15(pulmEvals.get(4).getFev1());
            setFvc5(pulmEvals.get(4).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate6(pulmEvals.get(5).getDate());
            setFev16(pulmEvals.get(5).getFev1());
            setFvc6(pulmEvals.get(5).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate7(pulmEvals.get(6).getDate());
            setFev17(pulmEvals.get(6).getFev1());
            setFvc7(pulmEvals.get(6).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate8(pulmEvals.get(7).getDate());
            setFev18(pulmEvals.get(7).getFev1());
            setFvc8(pulmEvals.get(7).getFvc());
        }
         i++;
       if(i < pulmEvals.size()){
            setDate9(pulmEvals.get(8).getDate());
            setFev19(pulmEvals.get(8).getFev1());
            setFvc9(pulmEvals.get(8).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate10(pulmEvals.get(9).getDate());
            setFev110(pulmEvals.get(9).getFev1());
            setFvc10(pulmEvals.get(9).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate11(pulmEvals.get(10).getDate());
            setFev111(pulmEvals.get(10).getFev1());
            setFvc11(pulmEvals.get(10).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate12(pulmEvals.get(11).getDate());
            setFev112(pulmEvals.get(11).getFev1());
            setFvc12(pulmEvals.get(11).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate13(pulmEvals.get(12).getDate());
            setFev113(pulmEvals.get(12).getFev1());
            setFvc13(pulmEvals.get(12).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate14(pulmEvals.get(13).getDate());
            setFev114(pulmEvals.get(13).getFev1());
            setFvc14(pulmEvals.get(13).getFvc());
        }
        i++;
        if(i < pulmEvals.size()){
            setDate15(pulmEvals.get(14).getDate());
            setFev115(pulmEvals.get(14).getFev1());
            setFvc15(pulmEvals.get(14).getFvc());
        }
    }
    
    public String getParticipantID() {
        return pid;
    }
    
    public void setParticipantID( String id) {
        this.pid = id;
    }
    
    public Date getDate1() {
        return (Date) attributes.get("date1").getValue();
    }
    
    public void setDate1(Date date1) {
        attributes.get("date1").setValue(date1);
    }

    public VerificationStatus getDate1VerificationStatus() {
        return attributes.get("date1").getVerificationStatus();
    }
    
    public void setDate1VerificationStatus(VerificationStatus verificationStatus) {
        attributes.get("date1").setVerificationStatus(verificationStatus);
    }

    public String getDate1DccComment() {
        return (String) attributes.get("date1").getDccComment();
    }
    
    public void setDate1DccComment(String dccComment) {
        attributes.get("date1").setDccComment(dccComment);
    }

    public Date getDate2() {
        return (Date) attributes.get("date2").getValue();
    }
    
    public void setDate2(Date date2) {
        attributes.get("date2").setValue(date2);
    }

    public VerificationStatus getDate2VerificationStatus() {
        return attributes.get("date2").getVerificationStatus();
    }
    
    public void setDate2VerificationStatus(VerificationStatus verificationStatus) {
        attributes.get("date2").setVerificationStatus(verificationStatus);
    }

    public String getDate2DccComment() {
        return (String) attributes.get("date2").getDccComment();
    }
    
    public void setDate2DccComment(String dccComment) {
        attributes.get("date2").setDccComment(dccComment);
    }

    public Date getDate3() {
        return (Date) attributes.get("date3").getValue();
    }
    
    public void setDate3(Date date3) {
        attributes.get("date3").setValue(date3);
    }

    public VerificationStatus getDate3VerificationStatus() {
        return attributes.get("date3").getVerificationStatus();
    }
    
    public void setDate3VerificationStatus(VerificationStatus verificationStatus) {
        attributes.get("date3").setVerificationStatus(verificationStatus);
    }

    public String getDate3DccComment() {

src/main/webapp/about.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>About</title>
    </h:head>
    
    <ui:composition template="/template/template.xhtml">
        <ui:define name="body">
            <h:outputStylesheet library="css" name="ecpregistry.css" />

            <h1><font size="6">About the ECP Registry Software</font></h1>

            <p style="width: 750px; font-size: medium;">
                The Extracorporeal Photopheresis (ECP) for the Management of Progressive Bronchiolitis
                Obliterans Syndrome (BOS) in Medicare-Eligible Recipients of Lung Allografts software 
                was developed to assist sites participating in the ECP Registry Study to input their 
                participant's information into a centralized database.
            </p>
 
            <p style="font-size: medium;">
                Software Release Date:  <h:outputText value="#{versionControl.softwareReleaseDate}" >
                                            <f:convertDateTime type="date" pattern="MM/dd/yyyy"/>
                                        </h:outputText>

            </p>
            <p style="font-size: medium;">
                Software Version: <h:outputText value="#{versionControl.softwareVersionNumber}" />
            </p>

        </ui:define>
    </ui:composition>

</html>

src/main/webapp/adverseEventForm.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    
    <ui:composition template="./template/adverseEventFormTemplate.xhtml">
        <ui:define name="saeProtocolLink">
            <a href="ecpRegistryProtocol.xhtml#section6-4" target="_blank">see Protocol Section 6.4</a>
        </ui:define>
    </ui:composition>
</html>

src/main/webapp/eligibilityForm.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="./template/oldEligibilityFormTemplate.xhtml" />

</html>

src/main/webapp/eligibilityFormV7.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="./template/newEligibilityFormTemplate.xhtml" />

</html>

src/main/webapp/studyArmEligibilitySuccess.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    
    <ui:composition template="/template/template.xhtml">
        <ui:define name="body">
            
            <h:panelGrid rendered="#{calcController.enrollmentEligible}">
                <h1 style="color:red; font-size:24px;">Enrollment Determination Results</h1>
                <h2>This patient is now ENROLLED into the Study.</h2>

                <h:panelGrid rendered="#{calcController.ecpTreatmentArmEligible}">
                    <h1 style="color:red; font-size:24px;">Study Arm Eligibility Results</h1>
                    <h2>This patient is assigned to the "ECP Treatment Arm".  Please follow the</h2>
                    <h2>Protocol's treatment and evaluation procedures for ECP Treatment Arm participants.</h2>
                    <p>
                        <h:outputText value="Rate of lung function decline (Slope) = #{calcController.slope} ml / month"/>
                        <h:outputText value="Statistically significant rate of decline (P-Value less than 0.05) = #{calcController.PValue}"/>
                        <h:outputText value="Last FEV1 value = #{calcController.lastFev} ml"/>
                    </p>
                    <h2>This patient's participant identification number is ${calcController.participantID}.</h2>

                    <p style="width: 850px; font-size: large; color: red; font-weight: bold">Please make a NOTE of your patient's participant 
                            identification number: ${calcController.participantID}, because all interaction with the  
                            Washington University Academic Research Organization (ARO) concerning this participant will use this identifier.
                    </p>
                    <p style="width: 850px; font-size: large; color: red; font-weight: bold">
                        <u>Important and Time-Sensitive:</u> Please PRINT this subject's Confirmation of Eligibility (COE) Form, have an 
                        authorized physician investigator sign and date the COE form, and scan and upload the signed COE form along with 
                        the other Source Documents listed at the top of the COE Form.  Per <a href="ecpRegistryProtocol.xhtml#section3-7" target="_blank">Protocol Section 3.7</a>, submission of this signed 
                        COE Form with DCC Verification is required before ECP or any study-related invasive procedure (e.g. central venous catheter placement) may be performed.
                    </p>
                    <h:form >
                        <h:commandButton value="Go to the COE Form to Print" action="#{controller.registryLoginAction()}" />
                    </h:form>

                </h:panelGrid>

                <h:panelGrid  rendered="#{calcController.observationalArmEligible}">
                    <h1 style="color:red; font-size:24px;">Study Arm Assignment Results</h1>
                    <h2>This patient is assigned to the "Observational Arm".  This patient is not currently</h2>
                    <h2>eligible to receive ECP because the rate (slope) of FEV1 decline does not meet</h2>
                    <h2>the study Protocol's threshold to qualify to receive ECP (see <a href="ecpRegistryProtocol.xhtml#section3-6" target="_blank">Protocol Section 3.6</a>).</h2>
                    <p>
                        Eligibility failed on the following criterion:
                        <h:outputText value="#{calcController.rule}"/>
                    </p>
                    <p>
                        <h:outputText value="Rate of lung function decline (Slope) = #{calcController.slope} ml / month"/>
                        <h:outputText value="Statistically significant rate of decline (P-Value less than 0.05) = #{calcController.PValue}"/>
                        <h:outputText value="Last FEV1 value = #{calcController.lastFev} ml"/>
                    </p>
                    <h2>This patient's participant identification number is ${calcController.participantID}.</h2>

                    <p style="width: 850px; font-size: large; color: red; font-weight: bold">Please make a NOTE of your patient's participant 
                            identification number: ${calcController.participantID}, because all interaction with the  
                            Washington University Academic Research Organization (ARO) concerning this participant will use this identifier.
                    </p>
                    <p style="width: 850px; font-size: large; color: red; font-weight: bold">Please follow the Protocol’s treatment and evaluation 
                        procedures for Observation Arm patients, and enter all subsequent clinically obtained FEV-1 values into the Observation 
                        Pulmonary Evaluations Log.  If your patient exhibits further decline and you wish him/her to receive ECP, you may enter 
                        up to 4 additional FEV-1 values (spaced at least one week apart) into the Observation Pulmonary Evaluations Log and request 
                        a re-assessment of whether he/she has become eligible for the ECP Treatment Arm, per <a href="ecpRegistryProtocol.xhtml#section3-6" target="_blank">Protocol Section 3.6</a>.  Please contact 
                        your CCC nurse coordinator if you have questions.
                    </p>
                    <p style="width: 850px; font-size: large; color: red; font-weight: bold">
                        <u>Important and Time-Sensitive:</u> Please PRINT this subject's Confirmation of Eligibility (COE) Form, have an 
                        authorized physician investigator sign and date the COE form, and scan and upload the signed COE form along with 
                        the other Source Documents listed at the top of the COE Form.  Per <a href="ecpRegistryProtocol.xhtml#section3-7" target="_blank">Protocol Section 3.7</a>, submission of this signed 
                        COE Form is required.
                    </p>
                    <h:form >
                        <h:commandButton value="Go to the COE Form to Print" action="#{controller.registryLoginAction()}" />
                    </h:form>

                </h:panelGrid>
<!--
                <h:form >
                    <h:panelGrid columns="2">
                        <h:commandButton value="Enroll Patient..." action="# {calcController.enrollParticipantIntoECPStudyAction}" />
                        <h:commandButton value="Cancel" action="# {calcController.cancelCalculationAction()}" />
                    </h:panelGrid>
                </h:form>
 -->
            </h:panelGrid>
            
            
            


            <h:panelGrid  rendered="#{calcController.notEnrollmentEligible}">
                <h1 style="color:red; font-size:24px;">Enrollment Determination Results</h1>
                <h2>This patient is NOT eligible for enrolling into the study currently,</h2>
                <h2>based on their answers to the inclusion and exclusion criteria.</h2>
                <p>
<!--                    Eligibility failed on the following criterion:  -->
<!--                    <h:outputText value="# {calcController.rule}"/>  -->
                </p>
                <p>
<!--                    <h:outputText value="index = # {calcController.notEnrollmentEligible} "/>  -->
                </p>
                <h:form >
                    <h:panelGrid columns="2">
                        <h:commandButton value="Cancel" action="#{calcController.cancelCalculationAction()}" />
                    </h:panelGrid>
                </h:form>
            </h:panelGrid>
            

        </ui:define>
    </ui:composition>
    
</html>